### ISSUE TITLE
Error when importing on Electron

### ISSUE THREAD

**Issue by akd3vs** [dynamsoft-dbr/javascript-barcode#57]
Hello, we are building a PoC for a client that has an application in Electron but we cannot import the module, I've tried different ways to import it but it's always the same error, could you help me?

The error is:

`Uncaught TypeError: Cannot read property 'platform' of undefined`

Image of the stacktrace:
![image](https://user-images.githubusercontent.com/1646108/76576163-ee063180-6486-11ea-8d27-63d0067aad19.png)

Thanks in advance!

**Comment by Keillion** [comment]
Hi, sorry for that we haven't tried compatibility with electron.
I'm looking at it. 

However, before we done, there may be something can be done to walk around the bug. I haven't test because I need some time to read electron's doc.

If you want dbrjs work in Node.js side:
* Define `global.process.release.name` as any `true` value, like "Tom" but not "".
* Then require `dist/dbr.mjs`.

If you want dbrjs work in browser side.
* Define `navigator.vendor`, `navigator.userAgent` and `navigator.platform` before import `dist/dbr.browser.js`.

Hope this helps.

**Comment by akd3vs** [comment]
@Keillion Yeah, I tried to define the things it says that were missing. We are trying to use it only as browser.

Thanks for the quick reply!

**Comment by Keillion** [comment]
Try this: https://github.com/dynamsoft-rd-0/dbrjs-electron
In main process, dbrjs works like in a node environment.
In renderer process, dbrjs works like in a web environment.

**Comment by akd3vs** [comment]
@Keillion I think it worked, but now I'm getting this error:
![image](https://user-images.githubusercontent.com/1646108/76637374-3c134780-6510-11ea-91b7-fc0d0765d588.png)

this is our setup:
![image](https://user-images.githubusercontent.com/1646108/76637418-577e5280-6510-11ea-849e-d9f1da96b6ec.png)
![image](https://user-images.githubusercontent.com/1646108/76637461-68c75f00-6510-11ea-9f0e-cd64b1d009e2.png)

Also, we are using Electron 7, if that helps.

**Comment by Keillion** [comment]
@akd3vs If everything goes well, we will release 7.3.0-v3 in about a week or two.

**Comment by akd3vs** [comment]
> @akd3vs If everything goes well, we will release 7.3.0-v3 in about a week or two.

In the meantime, can we keep using your fork?

**Comment by Keillion** [comment]
@akd3vs  Yes, of course.

**Comment by yushulx** [comment]
@akd3vs the issue is fixed. Please install the latest version 7.3.0-v4.

**Comment by Keillion** [comment]
Sample address:
https://github.com/dynamsoft-dbr/javascript-barcode/tree/master/example/hybird/electron
